### ISSUE TITLE
Implement compatibility with third party rank plugins

### ISSUE THREAD

**Issue by crashzk** [KillStr3aK/scoreboardrank#1]
It would be interesting to implement compatibility with rank plugins to show the players rank in the score based on their rank points.

Ranks that could be compatible are:
- Levels Ranks Core
- RankMe Kento

# HOW IT WORKS
My servers use Levels Ranks Core, based on their points the rank would automatically appear in the score on his rank, example:
```
"LevelRanks"
{
	"1"
	{
		"name" 		"Silver I"
		"index" 	"1"    
		"flag" 		"-1"
		"points"	"100"
    }
	
	"2"
    {
		"name" 		"Silver II"
		"index" 	"2"    
		"flag" 		"-1"
		"points"	"200"
    }
	
	"3"
    {
		"name" 		"Silver III"
		"index" 	"3"    
		"flag" 		"-1"
		"points"	"300"
    }
	
[...]
}
```
That is, it reached 100 points shows the Silver I rank, it reached 200 points shows the Silver II rank and so on.

**Comment by KillStr3aK** [comment]
Sounds good, I'm busy at the moment but support will be implemented for both system!
